SET NAMES utf8mb4;

-- 1. users
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role ENUM('CANDIDATO', 'EMPRESA', 'ADMIN') DEFAULT 'CANDIDATO',
    telefone VARCHAR(20) NULL,
    cidade VARCHAR(100) NULL,
    linkedin VARCHAR(255) NULL,
    portfolio VARCHAR(255) NULL,
    area VARCHAR(100) NULL,
    nivel_experiencia VARCHAR(50) NULL,
    sobre TEXT NULL,
    avatar_path VARCHAR(255) NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. empresas
CREATE TABLE IF NOT EXISTS empresas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    nome_fantasia VARCHAR(255) NOT NULL,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    email_contato VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NULL,
    site VARCHAR(255) NULL,
    cidade VARCHAR(100) NULL,
    estado VARCHAR(2) NULL,
    setor VARCHAR(100) NULL,
    num_funcionarios VARCHAR(50) NULL,
    descricao TEXT NULL,
    logo_path VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. vagas
CREATE TABLE IF NOT EXISTS vagas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    cargo VARCHAR(100) NULL,
    descricao TEXT NOT NULL,
    requisitos TEXT NULL,
    diferenciais TEXT NULL,
    beneficios TEXT NULL,
    salario_min DECIMAL(10,2) NULL,
    salario_max DECIMAL(10,2) NULL,
    tipo_contrato VARCHAR(50) NOT NULL,
    tipo_vaga VARCHAR(50) DEFAULT 'PRESENCIAL',
    experiencia VARCHAR(50) DEFAULT 'SEM_EXPERIENCIA',
    carga_horaria VARCHAR(100) NULL,
    area VARCHAR(100) NULL,
    nivel VARCHAR(50) NULL,
    cidade VARCHAR(100) DEFAULT 'Porto Ferreira',
    estado VARCHAR(2) DEFAULT 'SP',
    status ENUM('ATIVA', 'PAUSADA', 'CONCLUIDA', 'EXPIRADA') DEFAULT 'ATIVA',
    data_expiracao DATE NULL,
    publicada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. applications
CREATE TABLE IF NOT EXISTS applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vaga_id INT NOT NULL,
    user_id INT NOT NULL,
    mensagem TEXT NULL,
    curriculo_path VARCHAR(255) NULL,
    linkedin VARCHAR(255) NULL,
    portfolio VARCHAR(255) NULL,
    telefone VARCHAR(20) NULL,
    status ENUM('PENDENTE', 'EM_ANALISE', 'APROVADO', 'RECUSADO') DEFAULT 'PENDENTE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. favorites
CREATE TABLE IF NOT EXISTS favorites (
    user_id INT NOT NULL,
    vaga_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, vaga_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. password_resets
CREATE TABLE IF NOT EXISTS password_resets (
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
