-- Limpeza completa do banco de dados (respeitando FKs)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE email_verifications;
TRUNCATE TABLE password_resets;
TRUNCATE TABLE favorites;
TRUNCATE TABLE applications;
TRUNCATE TABLE vagas;
TRUNCATE TABLE empresas;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

-- Senha para todos: Admin@1234
-- Hash gerado via password_hash('Admin@1234', PASSWORD_DEFAULT)
SET @senha_padrao = '$2y$10$E8gv9FFOllIplybesNJbpe.OCmTVLG1mu99caq750zOT7/Rb3quuW';

-- 4 contas de empresa
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES
('Tech Solutions', 'empresa1@admin.com', @senha_padrao, 'EMPRESA', 1, NOW()),
('Porto Empregos', 'empresa2@admin.com', @senha_padrao, 'EMPRESA', 1, NOW()),
('Indústria Porto', 'empresa3@admin.com', @senha_padrao, 'EMPRESA', 1, NOW()),
('Comércio & Cia', 'empresa4@admin.com', @senha_padrao, 'EMPRESA', 1, NOW());

-- 4 contas de candidato
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES
('Ana Silva', 'candidato1@admin.com', @senha_padrao, 'CANDIDATO', 1, NOW()),
('Bruno Costa', 'candidato2@admin.com', @senha_padrao, 'CANDIDATO', 1, NOW()),
('Carla Mendes', 'candidato3@admin.com', @senha_padrao, 'CANDIDATO', 1, NOW()),
('Diego Rocha', 'candidato4@admin.com', @senha_padrao, 'CANDIDATO', 1, NOW());

-- 4 registros em empresas (vinculados aos usuários empresa)
INSERT INTO empresas (user_id, nome_fantasia, razao_social, cnpj, email_contato, cidade, estado, created_at)
VALUES
((SELECT id FROM users WHERE email='empresa1@admin.com'), 'Tech Solutions Porto Ferreira', 'Tech Solutions LTDA', '11.111.111/0001-11', 'empresa1@admin.com', 'Porto Ferreira', 'SP', NOW()),
((SELECT id FROM users WHERE email='empresa2@admin.com'), 'Porto Empregos', 'Porto Empregos LTDA', '22.222.222/0002-22', 'empresa2@admin.com', 'Porto Ferreira', 'SP', NOW()),
((SELECT id FROM users WHERE email='empresa3@admin.com'), 'Indústria Porto Ferreira', 'Indústria Porto LTDA', '33.333.333/0003-33', 'empresa3@admin.com', 'Porto Ferreira', 'SP', NOW()),
((SELECT id FROM users WHERE email='empresa4@admin.com'), 'Comércio & Cia Porto Ferreira', 'Comércio e Cia LTDA', '44.444.444/0004-44', 'empresa4@admin.com', 'Porto Ferreira', 'SP', NOW());

-- Atualiza empresa_id nos usuários empresa para facilitar o vínculo
UPDATE users u
INNER JOIN empresas e ON e.user_id = u.id
SET u.empresa_id = e.id
WHERE u.role = 'EMPRESA';

-- 40 vagas bem elaboradas (10 por empresa)

-- Empresa 1: Tech Solutions (Foco em TI e Administrativo)
SET @empresa1 = (SELECT id FROM empresas WHERE email_contato='empresa1@admin.com');

INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES
(@empresa1, 'Analista de Suporte Júnior', 'Analista de Suporte', 'TI', 'Estamos em busca de um Analista de Suporte para auxiliar nossos clientes internos e externos.\nResponsável por manutenção de hardware, software e suporte em redes locais.\nTrabalho em equipe dinâmica e ambiente inovador.', '- Ensino Superior em TI (cursando ou completo)\n- Conhecimento básico em redes\n- Pacote Office avançado\n- Boa comunicação interpessoal', '- Plano de Saúde\n- Vale Refeição\n- Seguro de Vida', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 2200.00, 2800.00),
(@empresa1, 'Desenvolvedor Full Stack PHP', 'Desenvolvedor', 'TI', 'Buscamos desenvolvedor proativo para atuar em projetos de e-commerce e sistemas internos.\nFoco em PHP moderno, MySQL e frameworks JavaScript (Vue ou React).\nParticipação em todas as etapas do ciclo de desenvolvimento.', '- PHP 8+\n- MySQL / PostgreSQL\n- HTML/CSS/JS\n- Git / GitHub', '- Home Office (Híbrido)\n- Bônus por Metas\n- Cursos de Especialização', 'CLT', 'HIBRIDO', 'Pleno', '1_A_3_ANOS', '40h semanais', 4500.00, 6500.00),
(@empresa1, 'Auxiliar Administrativo', 'Auxiliar Administrativo', 'Administração', 'Atendimento telefônico, organização de documentos e auxílio no faturamento.\nUso constante de planilhas de controle e sistema ERP da empresa.\nOrganização de reuniões e suporte à diretoria.', '- Ensino Médio completo\n- Conhecimento em Excel\n- Boa escrita\n- Organização extrema', '- Vale Transporte\n- Cesta Básica\n- Convênio Farmácia', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1600.00, 1900.00),
(@empresa1, 'Técnico de Infraestrutura', 'Técnico de TI', 'TI', 'Manutenção de servidores e cabeamento estruturado.\nInstalação de câmeras e sistemas de segurança digital.\nSuporte avançado a sistemas operacionais Windows e Linux.', '- Formação Técnica em TI\n- Experiência com Mikrotik\n- CNH B\n- Disponibilidade para viagens curtas', '- Veículo da empresa\n- Diárias de Viagem\n- Seguro de Vida', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800.00, 3500.00),
(@empresa1, 'Secretária Executiva', 'Secretária', 'Administração', 'Gestão de agenda da diretoria, recepção de clientes e organização de eventos corporativos.\nRedação de ofícios e atas de reuniões.\nControle de viagens e estadias.', '- Inglês intermediário\n- Experiência anterior na função\n- Ensino Superior completo ou cursando\n- Discrição e profissionalismo', '- Plano Odontológico\n- PLR Semestral\n- Refeitório no local', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 3000.00, 4200.00),
(@empresa1, 'Analista Financeiro', 'Analista Financeiro', 'Administração', 'Conciliação bancária, contas a pagar e receber e emissão de notas fiscais.\nAuxílio no fechamento contábil e gestão de fluxo de caixa.\nRelacionamento com bancos e fornecedores.', '- Formação em Administração ou Contábeis\n- Excel Avançado\n- Experiência com ERP\n- Perfil analítico', '- Plano de Saúde\n- Vale Alimentação\n- Auxílio Educação', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3500.00, 4800.00),
(@empresa1, 'Web Designer', 'Designer', 'Design', 'Criação de interfaces para sites e landing pages.\nDesenvolvimento de banners para redes sociais e peças de marketing digital.\nManutenção visual de sistemas internos.', '- Domínio de Figma ou Adobe XD\n- Photoshop e Illustrator\n- Noções de UX/UI\n- Portfólio atualizado', '- Bônus por performance\n- Horário flexível\n- Day off no aniversário', 'CLT', 'REMOTO', 'Pleno', '1_A_3_ANOS', '40h semanais', 3200.00, 4500.00),
(@empresa1, 'Estagiário de Programação', 'Estagiário', 'TI', 'Auxílio na correção de bugs e implementação de pequenas features.\nAprendizado prático em ambiente profissional com mentoria de seniores.\nFoco em desenvolvimento web moderno.', '- Cursando TI (noturno)\n- Lógica de programação sólida\n- Vontade de aprender\n- Proatividade', '- Bolsa Auxílio\n- Seguro de Vida\n- Possibilidade de Efetivação', 'Estágio', 'HIBRIDO', 'Sem experiência', 'SEM_EXPERIENCIA', '30h semanais', 1000.00, 1200.00),
(@empresa1, 'Gerente de TI', 'Gerente', 'TI', 'Gestão de equipe de desenvolvimento e suporte.\nPlanejamento estratégico de infraestrutura e segurança da informação.\nGestão de contratos com fornecedores de tecnologia.', '- Pós-graduação na área\n- Experiência em liderança de equipes\n- Inglês Avançado\n- Visão de negócio', '- Carro da empresa\n- Notebook e Celular\n- Bônus agressivo por KPIs', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 8000.00, 12000.00),
(@empresa1, 'Analista de Dados (BI)', 'Analista de BI', 'TI', 'Criação de dashboards e relatórios para tomada de decisão estratégica.\nExtração e tratamento de dados de diversas fontes.\nIdentificação de padrões e insights de negócio.', '- SQL Avançado\n- Power BI ou Tableau\n- Conhecimento em Estatística\n- Python para análise de dados', '- Participação nos Lucros\n- Auxílio Inglês\n- Academia (Gympass)', 'PJ', 'REMOTO', 'Sênior', 'MAIS_DE_3_ANOS', '40h semanais', 6000.00, 9000.00);

-- Empresa 2: Porto Empregos (Foco em Comércio, Serviços e Logística)
SET @empresa2 = (SELECT id FROM empresas WHERE email_contato='empresa2@admin.com');

INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES
(@empresa2, 'Vendedor de Loja', 'Vendedor', 'Comércio', 'Atendimento ao público em loja de decoração e presentes.\nOrganização de vitrines e controle de estoque do setor.\nFechamento de vendas e cadastro de clientes no sistema.', '- Ensino Médio completo\n- Disponibilidade de horário (incluindo sábados)\n- Simpatia e boa dicção\n- Gosto por vendas', '- Comissão sobre vendas\n- Vale Transporte\n- Treinamentos constantes', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500.00, 2500.00),
(@empresa2, 'Motorista Entregador (Cat C/D)', 'Motorista', 'Logística', 'Entregas de mercadorias em Porto Ferreira e região.\nConferência de notas fiscais e carga/descarga eventual.\nZelar pela manutenção básica do veículo da empresa.', '- CNH C ou D válida\n- Experiência com caminhão\n- Conhecimento da região\n- Responsabilidade no trânsito', '- Vale Refeição\n- Diárias de viagem\n- Seguro de Vida', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2500.00, 3200.00),
(@empresa2, 'Operador de Caixa', 'Caixa', 'Comércio', 'Operação de caixa em supermercado de grande porte.\nRecebimento de valores, abertura e fechamento de caixa.\nAtendimento cordial ao cliente e oferta de produtos promocionais.', '- Ensino Médio completo\n- Agilidade numérica\n- Experiência anterior será diferencial\n- Residir em Porto Ferreira', '- Quebra de Caixa\n- Vale Transporte\n- Auxílio Creche', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1600.00, 1850.00),
(@empresa2, 'Estoquista / Conferente', 'Estoquista', 'Logística', 'Recebimento de mercadorias, conferência com nota fiscal e organização de prateleiras.\nSeparação de pedidos para expedição.\nControle de inventário cíclico.', '- Ensino Médio\n- Proatividade e força física\n- Noções de informática\n- Atenção a detalhes', '- Cesta Básica\n- Vale Refeição\n- Convênio Médico', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 1700.00, 2000.00),
(@empresa2, 'Auxiliar de Limpeza', 'Auxiliar de Limpeza', 'Serviços Gerais', 'Limpeza e conservação de ambientes de escritório e áreas comuns.\nControle de estoque de materiais de limpeza.\nZelar pela higiene e organização das dependências.', '- Alfabetizado\n- Experiência na função\n- Residir em Porto Ferreira\n- Disposição para trabalho físico', '- Vale Transporte\n- Uniforme completo\n- Cesta Básica', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1450.00, 1600.00),
(@empresa2, 'Recepcionista de Consultório', 'Recepcionista', 'Saúde', 'Agendamento de consultas, atendimento telefônico e recepção de pacientes.\nOrganização de prontuários e autorização de guias de convênio.\nLimpeza da área de espera.', '- Ensino Médio completo\n- Informática básica\n- Cordialidade e paciência\n- Organização', '- Vale Transporte\n- Convênio Médico\n- Insalubridade (se aplicável)', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1650.00, 1900.00),
(@empresa2, 'Fisioterapeuta', 'Fisioterapeuta', 'Saúde', 'Atendimento clínico em clínica de reabilitação física.\nRealização de avaliações e planos de tratamento.\nOrientação de pacientes em exercícios terapêuticos.', '- Graduação completa em Fisioterapia\n- Registro ativo no CREFITO\n- Desejável especialização em Ortopedia\n- Pontualidade', '- Honorários por atendimento\n- Ambiente climatizado\n- Equipamentos modernos', 'PJ', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '30h semanais', 3000.00, 5000.00),
(@empresa2, 'Cozinheiro(a)', 'Cozinheiro', 'Comércio', 'Preparação de pratos à la carte e self-service em restaurante central.\nGestão da equipe de auxiliares e controle de estoque de insumos.\nGarantir as normas de vigilância sanitária.', '- Experiência comprovada como cozinheiro\n- Curso de Manipulação de Alimentos\n- Liderança de equipe\n- Criatividade culinária', '- Refeição no local\n- Caixinha (Gorjetas)\n- Vale Transporte', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2200.00, 3500.00),
(@empresa2, 'Analista de RH (Recrutamento)', 'Analista de RH', 'RH', 'Triagem de currículos, realização de entrevistas e integração de novos colaboradores.\nApoio nas rotinas de departamento pessoal e clima organizacional.\nDivulgação de vagas em canais estratégicos.', '- Formação em Psicologia ou RH\n- Experiência em R&S\n- Noções de leis trabalhistas\n- Boa oratória', '- Auxílio Educação\n- Plano de Saúde\n- Vale Alimentação', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800.00, 3800.00),
(@empresa2, 'Gerente de Loja', 'Gerente', 'Comércio', 'Gestão completa de unidade de varejo, incluindo equipe, estoque e metas de vendas.\nTreinamento de funcionários e gestão de conflitos.\nRelatórios de performance para a diretoria.', '- Experiência em gestão de varejo\n- Foco em resultados\n- Ensino Superior desejável\n- Disponibilidade de horário', '- Participação nos lucros\n- Veículo para uso profissional\n- Convênio Odontológico', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4500.00, 7000.00);

-- Empresa 3: Indústria Porto (Foco em Produção e Manutenção)
SET @empresa3 = (SELECT id FROM empresas WHERE email_contato='empresa3@admin.com');

INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES
(@empresa3, 'Operador de Forno Cerâmico', 'Operador de Forno', 'Produção', 'Operação de fornos contínuos em indústria de cerâmica artística.\nControle de temperatura e ciclo de queima das peças.\nInspeção visual das peças após a queima.', '- Experiência em cerâmica\n- Disponibilidade para turnos (revezamento)\n- Residir em Porto Ferreira\n- Atenção técnica', '- Adicional Noturno\n- Cesta Básica Robustecida\n- Plano de Saúde', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2000.00, 2600.00),
(@empresa3, 'Auxiliar de Produção (Geral)', 'Auxiliar de Produção', 'Produção', 'Atuar em diversas etapas da linha de produção: moldagem, acabamento e embalagem.\nTransporte interno de materiais e organização do setor de trabalho.\nCarga e descarga de caminhões.', '- Disposição física\n- Ensino Fundamental completo\n- Pontualidade britânica\n- Vontade de crescer na indústria', '- Refeitório no local\n- Vale Transporte\n- Prêmio Assiduidade', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1550.00, 1800.00),
(@empresa3, 'Pintor Artístico (Cerâmica)', 'Pintor', 'Produção', 'Pintura manual de peças de cerâmica conforme modelos pré-definidos.\nUso de tintas e esmaltes específicos para alta temperatura.\nAcabamento detalhado e artístico das peças.', '- Habilidade manual e artística\n- Experiência com pintura manual\n- Paciência e detalhismo\n- Teste prático no local', '- Ambiente criativo\n- Bônus por produtividade\n- Convênio Farmácia', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 1800.00, 2500.00),
(@empresa3, 'Eletricista de Manutenção', 'Eletricista', 'Produção', 'Manutenção corretiva e preventiva de máquinas industriais e motores.\nInstalações elétricas em baixa e média tensão.\nLeitura e interpretação de esquemas elétricos.', '- Curso Técnico em Elétrica ou Eletromecânica\n- NR10 válida\n- Experiência em indústria\n- Proatividade', '- Periculosidade (30%)\n- Plano de Saúde\n- Vale Alimentação', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800.00, 4000.00),
(@empresa3, 'Mecânico Industrial', 'Mecânico', 'Produção', 'Manutenção de prensas, compressores e sistemas pneumáticos.\nLubrificação de máquinas e troca de rolamentos/correias.\nSolda básica e pequenos reparos em estruturas.', '- Curso de Mecânica Industrial (SENAI)\n- Experiência em manutenção de fábrica\n- Conhecimento em pneumática\n- CNH B', '- Vale Refeição\n- Seguro de Vida\n- Auxílio Ferramentas', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2700.00, 3800.00),
(@empresa3, 'Líder de Expedição', 'Líder', 'Logística', 'Coordenação da equipe de carregamento e conferência de pedidos.\nEmissão de romaneios e notas fiscais de saída.\nGestão de estoque de produtos acabados.', '- Experiência em logística industrial\n- Liderança de equipes\n- Domínio de sistemas ERP\n- Organização', '- Adicional de Cargo de Confiança\n- PLR Anual\n- Convênio Odontológico', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 3200.00, 4500.00),
(@empresa3, 'Analista de Qualidade', 'Analista de Qualidade', 'Produção', 'Inspeção de matéria-prima e produtos acabados conforme normas.\nImplantação de melhorias nos processos produtivos.\nTreinamento de funcionários em boas práticas de fabricação.', '- Ensino Superior em Engenharia ou Gestão da Produção\n- Conhecimento em ferramentas da qualidade\n- Experiência em indústria cerâmica será diferencial\n- Perfil rigoroso', '- Vale Alimentação\n- Plano de Saúde\n- Auxílio Creche', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3000.00, 4200.00),
(@empresa3, 'Torneiro Mecânico', 'Torneiro', 'Produção', 'Uso de torno convencional para fabricação de peças de reposição industrial.\nLeitura de desenhos técnicos e uso de instrumentos de medição.\nZelar pelas ferramentas e máquinas da oficina.', '- Curso de Torneiro Mecânico\n- Experiência comprovada\n- Precisão técnica\n- Disponibilidade imediata', '- Insalubridade\n- Cesta Básica\n- Café da manhã na empresa', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2800.00, 3900.00),
(@empresa3, 'Assistente de PCP', 'Assistente', 'Produção', 'Auxílio no Planejamento e Controle da Produção.\nLançamento de ordens de produção e controle de prazos.\nAcompanhamento do fluxo de materiais entre setores.', '- Estudante de Engenharia ou Administração\n- Excel intermediário\n- Boa comunicação\n- Senso de urgência', '- Bolsa Auxílio competitiva\n- Possibilidade de crescimento\n- Seguro de Vida', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 1800.00, 2300.00),
(@empresa3, 'Encarregado de Produção', 'Encarregado', 'Produção', 'Gestão direta da linha de produção, garantindo metas e segurança.\nGestão de pessoal (escalas, faltas, treinamentos).\nApoio à gerência industrial em melhorias.', '- Vasta experiência em chão de fábrica\n- Habilidade em gestão de pessoas\n- Resolução de conflitos\n- Visão sistêmica', '- PLR\n- Veículo da empresa\n- Plano de Saúde Top', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4500.00, 6500.00);

-- Empresa 4: Comércio & Cia (Foco em Comércio, Educação e Geral)
SET @empresa4 = (SELECT id FROM empresas WHERE email_contato='empresa4@admin.com');

INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES
(@empresa4, 'Professor(a) de Inglês', 'Professor', 'Educação', 'Ministrar aulas para crianças, jovens e adultos em escola de idiomas.\nPreparação de aulas dinâmicas e correção de exercícios.\nParticipação em treinamentos pedagógicos da rede.', '- Fluência no idioma\n- Vivência no exterior será diferencial\n- Gosto pelo ensino\n- Disponibilidade aos sábados', '- Vale Transporte\n- Desconto em cursos da escola\n- Treinamentos metodológicos', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '20h a 40h semanais', 1800.00, 3500.00),
(@empresa4, 'Monitor(a) Escolar', 'Monitor', 'Educação', 'Auxílio aos professores em sala de aula e supervisão de alunos no pátio.\nOrganização de materiais pedagógicos e apoio em eventos escolares.\nGarantir a segurança e bem-estar das crianças.', '- Ensino Médio completo\n- Paciência e carinho com crianças\n- Proatividade\n- Cursando Pedagogia será diferencial', '- Vale Transporte\n- Cesta Básica\n- Convênio Farmácia', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500.00, 1700.00),
(@empresa4, 'Vendedor de Veículos', 'Vendedor', 'Comércio', 'Atendimento a clientes em concessionária de Porto Ferreira.\nDemonstração de veículos, realização de test-drives e negociação de valores.\nProspecção ativa de clientes e acompanhamento de leads.', '- Experiência em vendas consultivas\n- CNH B válida\n- Boa lábia e poder de negociação\n- Conhecimento básico de mecânica', '- Comissões agressivas\n- Treinamentos de fábrica\n- Plano de Saúde', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2000.00, 8000.00),
(@empresa4, 'Repositor de Mercadorias', 'Repositor', 'Comércio', 'Reposição de produtos em prateleiras de supermercado/loja.\nVerificação de datas de validade e precificação.\nOrganização de depósitos e limpeza de gôndolas.', '- Agilidade e proatividade\n- Disponibilidade de horário\n- Residir em Porto Ferreira\n- Atenção a detalhes', '- Vale Transporte\n- Refeição subsidiada\n- Plano Odontológico', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1550.00, 1750.00),
(@empresa4, 'Telemarketing Ativo', 'Operador de Telemarketing', 'Comércio', 'Realização de chamadas para oferta de serviços de internet e telefonia.\nRegistro de interações no sistema e fechamento de vendas por telefone.\nTrabalho com metas diárias e mensais.', '- Boa dicção e persistência\n- Ensino Médio completo\n- Gosto por desafios\n- Foco em resultados', '- Salário Fixo + Variável\n- VT e VR\n- Convênio com faculdades', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '36h semanais', 1412.00, 2500.00),
(@empresa4, 'Auxiliar de Cozinha', 'Auxiliar de Cozinha', 'Serviços Gerais', 'Auxílio no preparo de alimentos, higienização de vegetais e limpeza da cozinha.\nLavagem de louças e utensílios.\nOrganização do estoque de alimentos.', '- Agilidade e higiene\n- Experiência básica em cozinha\n- Trabalho em equipe\n- Disponibilidade noturna', '- Refeição no local\n- Gorjetas rateadas\n- Vale Transporte', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500.00, 1750.00),
(@empresa4, 'Enfermeiro(a) do Trabalho', 'Enfermeiro', 'Saúde', 'Atendimento de primeiros socorros em indústria.\nRealização de exames periódicos e controle de atestados.\nTreinamentos de CIPA e segurança do trabalho.', '- Graduação em Enfermagem + Especialização em Enfermagem do Trabalho\n- COREN ativo\n- Experiência em indústria\n- Postura ética', '- Plano de Saúde Superior\n- Seguro de Vida\n- Vale Alimentação', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3800.00, 5500.00),
(@empresa4, 'Analista de Marketing Social', 'Analista de Marketing', 'Comércio', 'Gestão de redes sociais para grupo de empresas locais.\nCriação de conteúdo textual e gestão de tráfego pago (básico).\nAnálise de métricas e engajamento.', '- Ensino Superior em Marketing ou Publicidade\n- Domínio de Redes Sociais\n- Criatividade e boa escrita\n- Portfólio básico', '- Notebook da empresa\n- Home Office flexível\n- Cursos online', 'PJ', 'HIBRIDO', 'Pleno', '1_A_3_ANOS', '40h semanais', 2500.00, 4000.00),
(@empresa4, 'Padeiro / Confeiteiro', 'Padeiro', 'Comércio', 'Produção de pães, bolos e doces para padaria tradicional.\nControle de fermentação e fornos.\nGarantir a qualidade e o sabor dos produtos artesanais.', '- Experiência comprovada em padaria\n- Habilidade com massas e confeitaria\n- Organização e higiene\n- Disponibilidade para madrugada', '- Cesta Básica\n- Adicional de Horário\n- Vale Transporte', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2200.00, 3800.00),
(@empresa4, 'Coordenador Pedagógico', 'Coordenador', 'Educação', 'Gestão da equipe de professores e suporte aos pais e alunos.\nElaboração de planos de ensino e acompanhamento de metas educacionais.\nOrganização de eventos e formaturas.', '- Graduação em Pedagogia\n- Experiência em coordenação escolar\n- Liderança inspiradora\n- Organização extrema', '- PLR\n- Plano de Saúde\n- Auxílio Alimentação', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4000.00, 6000.00);

COMMIT;
