-- Limpeza completa do banco de dados
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE email_verifications;
TRUNCATE TABLE password_resets;
TRUNCATE TABLE favorites;
TRUNCATE TABLE applications;
TRUNCATE TABLE vagas;
TRUNCATE TABLE empresas;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

-- Hash para a senha 'Admin@1234'
SET @senha = '$2y$10$E8gv9FFOllIplybesNJbpe.OCmTVLG1mu99caq750zOT7/Rb3quuW';

-- Inserção de Usuários (Empresas)
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Tech Solutions', 'empresa1@admin.com', @senha, 'EMPRESA', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Porto Empregos', 'empresa2@admin.com', @senha, 'EMPRESA', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Indústria Porto', 'empresa3@admin.com', @senha, 'EMPRESA', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Comércio & Cia', 'empresa4@admin.com', @senha, 'EMPRESA', 1, NOW());

-- Inserção de Usuários (Candidatos)
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Ana Silva', 'candidato1@admin.com', @senha, 'CANDIDATO', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Bruno Costa', 'candidato2@admin.com', @senha, 'CANDIDATO', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Carla Mendes', 'candidato3@admin.com', @senha, 'CANDIDATO', 1, NOW());
INSERT INTO users (nome, email, senha, role, email_verified, created_at) VALUES ('Diego Rocha', 'candidato4@admin.com', @senha, 'CANDIDATO', 1, NOW());

-- Inserção de Empresas vinculadas aos usuários
INSERT INTO empresas (user_id, nome_fantasia, razao_social, cnpj, email_contato, cidade, estado, created_at) VALUES ((SELECT id FROM users WHERE email='empresa1@admin.com'), 'Tech Solutions Porto Ferreira', 'Tech Solutions LTDA', '11.111.111/0001-11', 'empresa1@admin.com', 'Porto Ferreira', 'SP', NOW());
INSERT INTO empresas (user_id, nome_fantasia, razao_social, cnpj, email_contato, cidade, estado, created_at) VALUES ((SELECT id FROM users WHERE email='empresa2@admin.com'), 'Porto Empregos', 'Porto Empregos LTDA', '22.222.222/0002-22', 'empresa2@admin.com', 'Porto Ferreira', 'SP', NOW());
INSERT INTO empresas (user_id, nome_fantasia, razao_social, cnpj, email_contato, cidade, estado, created_at) VALUES ((SELECT id FROM users WHERE email='empresa3@admin.com'), 'Indústria Porto Ferreira', 'Indústria Porto LTDA', '33.333.333/0003-33', 'empresa3@admin.com', 'Porto Ferreira', 'SP', NOW());
INSERT INTO empresas (user_id, nome_fantasia, razao_social, cnpj, email_contato, cidade, estado, created_at) VALUES ((SELECT id FROM users WHERE email='empresa4@admin.com'), 'Comércio & Cia Porto Ferreira', 'Comércio e Cia LTDA', '44.444.444/0004-44', 'empresa4@admin.com', 'Porto Ferreira', 'SP', NOW());

-- Atualização de empresa_id nos usuários empresa
UPDATE users u INNER JOIN empresas e ON e.user_id = u.id SET u.empresa_id = e.id WHERE u.role = 'EMPRESA';

-- Definição de IDs de empresa para as vagas
SET @e1 = (SELECT id FROM empresas WHERE email_contato='empresa1@admin.com');
SET @e2 = (SELECT id FROM empresas WHERE email_contato='empresa2@admin.com');
SET @e3 = (SELECT id FROM empresas WHERE email_contato='empresa3@admin.com');
SET @e4 = (SELECT id FROM empresas WHERE email_contato='empresa4@admin.com');

-- Vagas Empresa 1 (Tech Solutions)
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Analista de Suporte Júnior', 'Analista de Suporte', 'TI', 'Suporte a clientes internos e externos, manutenção de hardware e redes.', 'Ensino Superior em TI, básico em redes, Office avançado.', 'Plano de Saúde, VR, Seguro de Vida.', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 2200, 2800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Desenvolvedor Full Stack PHP', 'Desenvolvedor', 'TI', 'Projetos e-commerce e sistemas internos com PHP moderno.', 'PHP 8+, MySQL, HTML/CSS/JS, Git.', 'Home Office, Bônus, Cursos.', 'CLT', 'HIBRIDO', 'Pleno', '1_A_3_ANOS', '40h semanais', 4500, 6500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Auxiliar Administrativo', 'Auxiliar Administrativo', 'Administração', 'Atendimento, organização de documentos e auxílio faturamento.', 'Ensino Médio, Excel, boa escrita.', 'VT, Cesta Básica, Farmácia.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1600, 1900);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Técnico de Infraestrutura', 'Técnico de TI', 'TI', 'Manutenção de servidores e cabeamento estruturado.', 'Técnico em TI, Mikrotik, CNH B.', 'Veículo, Diárias, Seguro.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800, 3500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Secretária Executiva', 'Secretária', 'Administração', 'Gestão de agenda, recepção e organização de eventos.', 'Inglês, experiência na função, discrição.', 'Odonto, PLR, Refeitório.', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 3000, 4200);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Analista Financeiro', 'Analista Financeiro', 'Administração', 'Conciliação bancária, contas a pagar/receber e notas fiscais.', 'Formação Adm/Contábeis, Excel Avançado.', 'Saúde, Alimentação, Educação.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3500, 4800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Web Designer', 'Designer', 'Design', 'Interfaces para sites e banners sociais.', 'Figma, Photoshop, Illustrator.', 'Bônus, Flexibilidade, Day Off.', 'CLT', 'REMOTO', 'Pleno', '1_A_3_ANOS', '40h semanais', 3200, 4500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Estagiário de Programação', 'Estagiário', 'TI', 'Correção de bugs e pequenas features.', 'Cursando TI, lógica sólida.', 'Bolsa, Seguro, Efetivação.', 'Estágio', 'HIBRIDO', 'Sem experiência', 'SEM_EXPERIENCIA', '30h semanais', 1000, 1200);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Gerente de TI', 'Gerente', 'TI', 'Gestão de equipe e planejamento de infraestrutura.', 'Pós-graduação, liderança, Inglês Avançado.', 'Carro, Notebook, Bônus.', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 8000, 12000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e1, 'Analista de Dados (BI)', 'Analista de BI', 'TI', 'Dashboards e relatórios estratégicos.', 'SQL Avançado, Power BI, Estatística.', 'PLR, Auxílio Inglês, Gympass.', 'PJ', 'REMOTO', 'Sênior', 'MAIS_DE_3_ANOS', '40h semanais', 6000, 9000);

-- Vagas Empresa 2 (Porto Empregos)
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Vendedor de Loja', 'Vendedor', 'Comércio', 'Atendimento ao público e organização de vitrines.', 'Ensino Médio, disponibilidade horário.', 'Comissão, VT, Treinamentos.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500, 2500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Motorista Entregador (Cat C/D)', 'Motorista', 'Logística', 'Entregas regionais e conferência de notas.', 'CNH C/D, experiência caminhão.', 'Refeição, Diárias, Seguro.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2500, 3200);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Operador de Caixa', 'Caixa', 'Comércio', 'Operação de caixa e recebimento de valores.', 'Ensino Médio, agilidade numérica.', 'Quebra Caixa, VT, Auxílio Creche.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1600, 1850);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Estoquista / Conferente', 'Estoquista', 'Logística', 'Recebimento e conferência de mercadorias.', 'Ensino Médio, proatividade.', 'Cesta Básica, Refeição, Convênio.', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 1700, 2000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Auxiliar de Limpeza', 'Auxiliar de Limpeza', 'Serviços Gerais', 'Limpeza e conservação de ambientes.', 'Alfabetizado, experiência.', 'VT, Uniforme, Cesta Básica.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1450, 1600);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Recepcionista de Consultório', 'Recepcionista', 'Saúde', 'Agendamento e recepção de pacientes.', 'Ensino Médio, informática básica.', 'VT, Convênio Médico.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1650, 1900);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Fisioterapeuta', 'Fisioterapeuta', 'Saúde', 'Atendimento clínico e reabilitação.', 'Graduação Fisioterapia, CREFITO.', 'Honorários, Ambiente Climatizado.', 'PJ', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '30h semanais', 3000, 5000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Cozinheiro(a)', 'Cozinheiro', 'Comércio', 'Preparação de pratos à la carte e buffet.', 'Experiência comprovada, higiene.', 'Refeição, Gorjetas, VT.', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2200, 3500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Analista de RH (Recrutamento)', 'Analista de RH', 'RH', 'Triagem, entrevistas e integração.', 'Formação Psico/RH, exp. R&S.', 'Educação, Saúde, Alimentação.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800, 3800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e2, 'Gerente de Loja', 'Gerente', 'Comércio', 'Gestão de unidade, equipe e metas.', 'Exp. Gestão, foco resultados.', 'PLR, Veículo, Odonto.', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4500, 7000);

-- Vagas Empresa 3 (Indústria Porto)
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Operador de Forno Cerâmico', 'Operador de Forno', 'Produção', 'Operação de fornos contínuos.', 'Exp. cerâmica, disponibilidade turnos.', 'Adicional, Cesta Básica, Saúde.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2000, 2600);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Auxiliar de Produção (Geral)', 'Auxiliar de Produção', 'Produção', 'Moldagem, acabamento e embalagem.', 'Disposição física, Fundamental.', 'Refeitório, VT, Assiduidade.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1550, 1800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Pintor Artístico (Cerâmica)', 'Pintor', 'Produção', 'Pintura manual de peças.', 'Habilidade manual, exp. pintura.', 'Bônus, Farmácia.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 1800, 2500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Eletricista de Manutenção', 'Eletricista', 'Produção', 'Manutenção corretiva industrial.', 'Técnico Elétrica, NR10.', 'Periculosidade, Saúde, VR.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2800, 4000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Mecânico Industrial', 'Mecânico', 'Produção', 'Manutenção pneumática e máquinas.', 'Curso Mecânica, exp. fábrica.', 'Refeição, Seguro, Ferramentas.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2700, 3800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Líder de Expedição', 'Líder', 'Logística', 'Coordenação de carregamento.', 'Exp. Logística, liderança.', 'Gratificação, PLR, Odonto.', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 3200, 4500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Analista de Qualidade', 'Analista de Qualidade', 'Produção', 'Inspeção e melhoria de processos.', 'Engenharia, Qualidade.', 'Alimentação, Saúde, Creche.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3000, 4200);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Torneiro Mecânico', 'Torneiro', 'Produção', 'Fabricação de peças de reposição.', 'Curso Torneiro, experiência.', 'Insalubridade, Cesta, Café.', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2800, 3900);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Assistente de PCP', 'Assistente', 'Produção', 'Controle da produção e materiais.', 'Estudante Engenharia, Excel.', 'Bolsa, Crescimento.', 'CLT', 'PRESENCIAL', 'Júnior', '6_MESES_A_1_ANO', '44h semanais', 1800, 2300);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e3, 'Encarregado de Produção', 'Encarregado', 'Produção', 'Gestão direta de fábrica e metas.', 'Vasta experiência, gestão pessoas.', 'PLR, Veículo, Saúde.', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4500, 6500);

-- Vagas Empresa 4 (Comércio & Cia)
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Professor(a) de Inglês', 'Professor', 'Educação', 'Aulas para jovens e adultos.', 'Fluência, gosto pelo ensino.', 'VT, Descontos, Treinamentos.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '40h semanais', 1800, 3500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Monitor(a) Escolar', 'Monitor', 'Educação', 'Auxílio em sala e supervisão.', 'Ensino Médio, paciência.', 'VT, Cesta, Farmácia.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500, 1700);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Vendedor de Veículos', 'Vendedor', 'Comércio', 'Vendas e prospecção em concessionária.', 'Exp. Vendas, CNH B.', 'Comissões, Treinos, Saúde.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 2000, 8000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Repositor de Mercadorias', 'Repositor', 'Comércio', 'Reposição e precificação.', 'Agilidade, disponibilidade.', 'VT, Refeição, Odonto.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1550, 1750);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Telemarketing Ativo', 'Operador de Telemarketing', 'Comércio', 'Oferta de serviços por telefone.', 'Boa dicção, Ensino Médio.', 'Fixo + Variável, VT, VR.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '36h semanais', 1412, 2500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Auxiliar de Cozinha', 'Auxiliar de Cozinha', 'Serviços Gerais', 'Auxílio preparo e limpeza.', 'Agilidade, exp. básica.', 'Refeição, Gorjetas, VT.', 'CLT', 'PRESENCIAL', 'Júnior', 'SEM_EXPERIENCIA', '44h semanais', 1500, 1750);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Enfermeiro(a) do Trabalho', 'Enfermeiro', 'Saúde', 'Primeiros socorros industrial.', 'Graduação + Especialização.', 'Saúde Top, Seguro, VA.', 'CLT', 'PRESENCIAL', 'Pleno', '1_A_3_ANOS', '44h semanais', 3800, 5500);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Analista de Marketing Social', 'Analista de Marketing', 'Comércio', 'Gestão de redes e conteúdo.', 'Superior Marketing, Criatividade.', 'Notebook, Híbrido, Cursos.', 'PJ', 'HIBRIDO', 'Pleno', '1_A_3_ANOS', '40h semanais', 2500, 4000);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Padeiro / Confeiteiro', 'Padeiro', 'Comércio', 'Produção artesanal de pães.', 'Exp. comprovada, higiene.', 'Cesta, Adicional, VT.', 'CLT', 'PRESENCIAL', 'Sênior', 'MAIS_DE_3_ANOS', '44h semanais', 2200, 3800);
INSERT INTO vagas (empresa_id, titulo, cargo, area, descricao, requisitos, beneficios, tipo_contrato, tipo_vaga, nivel, experiencia, carga_horaria, salario_min, salario_max) VALUES (@e4, 'Coordenador Pedagógico', 'Coordenador', 'Educação', 'Gestão pedagógica e suporte.', 'Graduação Pedagogia, exp.', 'PLR, Saúde, Alimentação.', 'CLT', 'PRESENCIAL', 'Gestão', 'MAIS_DE_3_ANOS', '44h semanais', 4000, 6000);
